### ISSUE TITLE
找不到类

### ISSUE THREAD

**Issue by YandZD** [Gh0u1L5/WechatMagician#34]
魔法师大佬，自己编译安装找不到类是什么问题呢，错误log：
01-15 10:32:28.359 I/Xposed  ( 2119): -----------------
01-15 10:32:28.359 I/Xposed  ( 2119): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
01-15 10:32:29.368 I/Xposed  ( 2119): Detected ART runtime
01-15 10:32:29.373 I/Xposed  ( 2119): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
01-15 10:32:30.126 I/Xposed  ( 2119): Loading modules from /data/app/com.gh0u1l5.wechatmagician-2/base.apk
01-15 10:32:30.151 I/Xposed  ( 2119):   Loading class com.gh0u1l5.wechatmagician.backend.WechatHook
01-15 10:32:30.157 E/Xposed  ( 2119):     Failed to load class com.gh0u1l5.wechatmagician.backend.WechatHook
01-15 10:32:30.157 E/Xposed  ( 2119): java.lang.ClassNotFoundException: Didn't find class "com.gh0u1l5.wechatmagician.backend.WechatHook" on path: DexPathList[[zip file "/data/app/com.gh0u1l5.wechatmagician-2/base.apk"],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
01-15 10:32:30.157 E/Xposed  ( 2119): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-15 10:32:30.157 E/Xposed  ( 2119): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
01-15 10:32:30.157 E/Xposed  ( 2119): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-15 10:32:30.157 E/Xposed  ( 2119): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:524)
01-15 10:32:30.157 E/Xposed  ( 2119): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:454)
01-15 10:32:30.157 E/Xposed  ( 2119): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:96)
01-15 10:32:30.157 I/Xposed  ( 2119):   Loading class com.gh0u1l5.wechatmagician.backend.WechatResHook
01-15 10:32:30.158 E/Xposed  ( 2119):     Failed to load class com.gh0u1l5.wechatmagician.backend.WechatResHook
01-15 10:32:30.158 E/Xposed  ( 2119): java.lang.ClassNotFoundException: Didn't find class "com.gh0u1l5.wechatmagician.backend.WechatResHook" on path: DexPathList[[zip file "/data/app/com.gh0u1l5.wechatmagician-2/base.apk"],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
01-15 10:32:30.158 E/Xposed  ( 2119): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-15 10:32:30.158 E/Xposed  ( 2119): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
01-15 10:32:30.158 E/Xposed  ( 2119): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-15 10:32:30.158 E/Xposed  ( 2119): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:524)
01-15 10:32:30.158 E/Xposed  ( 2119): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:454)
01-15 10:32:30.158 E/Xposed  ( 2119): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:96)

**Comment by YandZD** [comment]
已解决
Please make sure to disable Instant Run (File -> Settings -> Build, Execution, Deployment -> Instant Run), otherwise your classes aren't included directly in the APK, but loaded via a stub application which Xposed can't handle.
