### ISSUE TITLE
Sony xzp8.0 软件正常  但是无法拦截朋友圈关键字 看不到快捷已读按钮

### ISSUE THREAD

**Issue by klcb2010** [Gh0u1L5/WechatMagician#47]
03-21 08:51:31.221 I/Xposed  ( 1883): Sorcery Xposed: not active
03-21 08:51:31.363 I/Xposed  ( 2799): Sorcery Xposed: not active
03-21 08:51:31.367 E/Xposed  (11907): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.internal.telephony.PhoneSubInfo
03-21 08:51:31.367 E/Xposed  (11907): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
03-21 08:51:31.367 E/Xposed  (11907): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
03-21 08:51:31.367 E/Xposed  (11907): 	at com.phoneinfo.changerpro.hooks.f.a(Unknown Source:45)
03-21 08:51:31.367 E/Xposed  (11907): 	at com.phoneinfo.changerpro.hooks.MainHook.handleLoadPackage(Unknown Source:29)
03-21 08:51:31.367 E/Xposed  (11907): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
03-21 08:51:31.367 E/Xposed  (11907): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
03-21 08:51:31.367 E/Xposed  (11907): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
03-21 08:51:31.367 E/Xposed  (11907): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
03-21 08:51:31.367 E/Xposed  (11907): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
03-21 08:51:31.367 E/Xposed  (11907): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
03-21 08:51:31.367 E/Xposed  (11907): 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
03-21 08:51:31.367 E/Xposed  (11907): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
03-21 08:51:31.367 E/Xposed  (11907): 	at android.os.Handler.dispatchMessage(Handler.java:105)
03-21 08:51:31.367 E/Xposed  (11907): 	at android.os.Looper.loop(Looper.java:251)
03-21 08:51:31.367 E/Xposed  (11907): 	at android.app.ActivityThread.main(ActivityThread.java:6563)
03-21 08:51:31.367 E/Xposed  (11907): 	at java.lang.reflect.Method.invoke(Native Method)
03-21 08:51:31.367 E/Xposed  (11907): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-21 08:51:31.367 E/Xposed  (11907): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
03-21 08:51:31.367 E/Xposed  (11907): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
03-21 08:51:31.367 E/Xposed  (11907): Caused by: java.lang.ClassNotFoundException: com.android.internal.telephony.PhoneSubInfo
03-21 08:51:31.367 E/Xposed  (11907): 	at java.lang.Class.classForName(Native Method)
03-21 08:51:31.367 E/Xposed  (11907): 	at java.lang.Class.forName(Class.java:453)
03-21 08:51:31.367 E/Xposed  (11907): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
03-21 08:51:31.367 E/Xposed  (11907): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
03-21 08:51:31.367 E/Xposed  (11907): 	... 18 more
03-21 08:51:31.367 E/Xposed  (11907): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.telephony.PhoneSubInfo" on path: DexPathList[[zip file "/data/app/ce.hesh.wechatUI-dS1ELS5rlJZg_s66T5y7oA==/base.apk"],nativeLibraryDirectories=[/data/app/ce.hesh.wechatUI-dS1ELS5rlJZg_s66T5y7oA==/lib/arm64, /system/lib64, /system/vendor/lib64]]
03-21 08:51:31.367 E/Xposed  (11907): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
03-21 08:51:31.367 E/Xposed  (11907): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-21 08:51:31.367 E/Xposed  (11907): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-21 08:51:31.367 E/Xposed  (11907): 	... 22 more
03-21 08:51:31.384 I/Xposed  (11907): === GG-Team MoreMock : SUKSES ===
03-21 08:51:31.392 I/Xposed  (11907): Sorcery Xposed: not active
03-21 08:51:45.339 I/Xposed  ( 9406): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:94) Activity onResume =	com.tencent.mm.ui.LauncherUI@5cf2e7e	
03-21 08:51:47.157 I/Xposed  ( 9406): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:94) Activity onResume =	com.tencent.mm.plugin.sns.ui.SnsTimeLineUI@564e72e	
03-21 08:52:42.769 I/Xposed  ( 3968): Sorcery Xposed: not active
03-21 08:52:43.779 I/Xposed  ( 7220): Sorcery Xposed: not active
03-21 08:52:48.259 E/Xposed  (12118): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.internal.telephony.PhoneSubInfo
03-21 08:52:48.259 E/Xposed  (12118): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
03-21 08:52:48.259 E/Xposed  (12118): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
03-21 08:52:48.259 E/Xposed  (12118): 	at com.phoneinfo.changerpro.hooks.f.a(Unknown Source:45)
03-21 08:52:48.259 E/Xposed  (12118): 	at com.phoneinfo.changerpro.hooks.MainHook.handleLoadPackage(Unknown Source:29)
03-21 08:52:48.259 E/Xposed  (12118): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
03-21 08:52:48.259 E/Xposed  (12118): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
03-21 08:52:48.259 E/Xposed  (12118): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
03-21 08:52:48.259 E/Xposed  (12118): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
03-21 08:52:48.259 E/Xposed  (12118): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
03-21 08:52:48.259 E/Xposed  (12118): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
03-21 08:52:48.259 E/Xposed  (12118): 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
03-21 08:52:48.259 E/Xposed  (12118): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
03-21 08:52:48.259 E/Xposed  (12118): 	at android.os.Handler.dispatchMessage(Handler.java:105)
03-21 08:52:48.259 E/Xposed  (12118): 	at android.os.Looper.loop(Looper.java:251)
03-21 08:52:48.259 E/Xposed  (12118): 	at android.app.ActivityThread.main(ActivityThread.java:6563)
03-21 08:52:48.259 E/Xposed  (12118): 	at java.lang.reflect.Method.invoke(Native Method)
03-21 08:52:48.259 E/Xposed  (12118): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-21 08:52:48.259 E/Xposed  (12118): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
03-21 08:52:48.259 E/Xposed  (12118): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
03-21 08:52:48.259 E/Xposed  (12118): Caused by: java.lang.ClassNotFoundException: com.android.internal.telephony.PhoneSubInfo
03-21 08:52:48.259 E/Xposed  (12118): 	at java.lang.Class.classForName(Native Method)
03-21 08:52:48.259 E/Xposed  (12118): 	at java.lang.Class.forName(Class.java:453)
03-21 08:52:48.259 E/Xposed  (12118): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
03-21 08:52:48.259 E/Xposed  (12118): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
03-21 08:52:48.259 E/Xposed  (12118): 	... 18 more
03-21 08:52:48.259 E/Xposed  (12118): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.telephony.PhoneSubInfo" on path: DexPathList[[zip file "/data/app/com.coolapk.market-SXCKIGGK0yokbMhmX58Gag==/base.apk"],nativeLibraryDirectories=[/data/app/com.coolapk.market-SXCKIGGK0yokbMhmX58Gag==/lib/arm, /data/app/com.coolapk.market-SXCKIGGK0yokbMhmX58Gag==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
03-21 08:52:48.259 E/Xposed  (12118): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
03-21 08:52:48.259 E/Xposed  (12118): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-21 08:52:48.259 E/Xposed  (12118): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-21 08:52:48.259 E/Xposed  (12118): 	... 22 more
03-21 08:52:48.285 I/Xposed  (12118): === GG-Team MoreMock : SUKSES ===
03-21 08:52:48.291 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.598 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.605 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.610 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.618 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.621 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.629 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.633 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.636 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.641 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.660 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.666 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.682 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.684 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.700 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.703 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.705 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.709 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.884 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.901 I/Xposed  (12118): Sorcery Xposed: not active
03-21 08:52:48.907 I/Xposed  (12118): Sorcery Xposed: not active

**Comment by klcb2010** [comment]
03-21 08:56:04.563 I/Xposed  ( 9406): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:94) Activity onResume =	com.tencent.mm.plugin.sns.ui.SnsTimeLineUI@feb0b4a	
03-21 08:56:13.354 I/Xposed  ( 9406): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:94) Activity onResume =	com.tencent.mm.plugin.sns.ui.SnsUploadUI@8d8674c	
03-21 08:56:16.709 I/Xposed  ( 9406): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:94) Activity onResume =	com.tencent.mm.plugin.sns.ui.SnsTimeLineUI@feb0b4a	
03-21 08:56:20.458 I/Xposed  ( 9406): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:94) Activity onResume =	com.tencent.mm.ui.LauncherUI@5cf2e7e	
03-21 08:57:24.683 I/Xposed  ( 9406): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:94) Activity onResume =	com.tencent.mm.ui.LauncherUI@5cf2e7e
