### ISSUE TITLE
[Bug] 无法在VXposed下正常工作

### ISSUE THREAD

**Issue by xfl03** [Gh0u1L5/WechatMagician#55]
## Bug反馈模板
1.  我当前的基本环境信息是
    * 手机型号：Xiaomi-Redmi Note 4X
    * Android 版本：7.0
    * Xposed 版本：91
    * Wechat 版本：6.6.6
    * Wechat Magician版本：2.8.0
    * VirtualXposed 版本：0.9.1  
  
2.  你遇到的问题是什么？（请描述完整操作与具体现象）

    在登录微信后，启动微信APP会持续黑屏，关闭此模块后恢复正常。

3.  Bug 触发后生成的 Xposed 日志
```
de.robv.android.xposed.XposedHelpers$InvocationTargetError: com.tencent.wcdb.database.SQLiteException: no such table: snsExtInfo3 (code 1, errno 0): , while compiling: DELETE FROM snsExtInfo3 WHERE local_flag=0
at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1271)
at com.gh0u1l5.wechatmagician.backend.plugins.SnsForward$onDatabaseOpened$1.invoke(SnsForward.kt:132)
...
Caused by: com.tencent.wcdb.database.SQLiteException: no such table: snsExtInfo3 (code 1, errno 0): , while compiling: DELETE FROM snsExtInfo3 WHERE local_flag=0
at com.tencent.wcdb.database.SQLiteConnection.nativePrepareStatement(Native Method)
at com.tencent.wcdb.database.SQLiteConnection.acquirePreparedStatement(SourceFile:971)
...
```

**Comment by Sodium-Aluminate** [comment]
同样问题。
1.  我当前的基本环境信息是
    * 手机型号：红米闹腾4（redmi note 4）
    * Android 版本：7.1.2 （API25）   Los 14.1-20180222-NIGHTLY-mido
    * Xposed 版本：89.2 （systemless）（magisk模块）
    * Wechat 版本：6.6.2
    * Wechat Magician版本：2.8.0

**Comment by kyoczp** [comment]
VXposed 只对此软件内的副本软件有作用，所以要在VXposed里面登录微信。

**Comment by xfl03** [comment]
@kyoczp 确定为内部微信
