### ISSUE TITLE
[bug] kotlin.KotlinNullPointerException: 消息存储器缓存和SQLite 数据库劫持无法启用。

### ISSUE THREAD

**Issue by MikeChongCan** [Gh0u1L5/WechatMagician#56]
请根据你的需求按对应模板填写问题，不按模板发的 issue 将可能被直接关闭。

## Bug反馈模板
0.  issue 标题请使用[Bug]XXXXXXX

    例子: [Bug]无法转发链接给朋友

1.  我当前的基本环境信息是
    * 手机型号：`Google Nexus 6`
    * Android 版本：`6.0.1 (SDK 23)`
    * Xposed 版本：`Starting Xposed version 86, compiled for SDK 23`
    * Wechat 版本：`6.6.6`
    * Wechat Magician版本：`2.8.0`

2.  你遇到的问题是什么？（请描述完整操作与具体现象）

   *消息存储器缓存* 和 *SQLite 数据库劫持* 无法启用。

![screenshot_20180416-145559](https://user-images.githubusercontent.com/2396817/38813337-90a8e8b8-4186-11e8-93e8-bf9d4305c336.png)

3.  Bug 触发后生成的 Xposed 日志
```bash
04-16 14:30:23.730 I/Xposed  (  388): -----------------
04-16 14:30:23.730 I/Xposed  (  388): Starting Xposed version 86, compiled for SDK 23
04-16 14:30:23.730 I/Xposed  (  388): Device: Nexus 6 (motorola), Android version 6.0.1 (SDK 23)
04-16 14:30:23.730 I/Xposed  (  388): ROM: MOB31E
04-16 14:30:23.730 I/Xposed  (  388): Build fingerprint: google/shamu/shamu:6.0.1/MOB31E/3142026:user/release-keys
04-16 14:30:23.730 I/Xposed  (  388): Platform: armeabi-v7a, 32-bit binary, system server: yes
04-16 14:30:23.730 I/Xposed  (  388): SELinux enabled: yes, enforcing: yes
04-16 14:30:23.741 I/Xposed  (  388): -----------------
04-16 14:30:23.741 I/Xposed  (  388): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-16 14:30:24.518 I/Xposed  (  388): Detected ART runtime
04-16 14:30:24.551 I/Xposed  (  388): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-16 14:30:25.083 I/Xposed  (  388): Loading modules from /data/app/com.gh0u1l5.wechatmagician-1/base.apk
04-16 14:30:25.312 I/Xposed  (  388):   Loading class com.gh0u1l5.wechatmagician.backend.WechatHook
04-16 14:31:06.053 I/Xposed  ( 2167): Wechat Magician: process = com.tencent.mm, version = 2.8.0
04-16 14:31:06.434 I/Xposed  ( 2167): Wechat SpellBook: 14 plugins, 2 hookers.
04-16 14:31:10.589 E/Xposed  ( 2167): kotlin.KotlinNullPointerException
04-16 14:31:10.589 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.booter.notification.Classes$MMNotification_MessageHandler$2.invoke(Classes.kt:19)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.booter.notification.Classes$MMNotification_MessageHandler$2.invoke(Classes.kt:11)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.booter.notification.Classes.getMMNotification_MessageHandler(Classes.kt)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.hookers.Notifications$MessageHandlerHooker$1.invoke(Notifications.kt:26)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.hookers.Notifications$MessageHandlerHooker$1.invoke(Notifications.kt:13)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:37)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:11)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$2.invoke(XposedUtil.kt:25)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$2.invoke(XposedUtil.kt:11)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil$tryAsynchronously$1.invoke(BasicUtil.kt:18)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil$tryAsynchronously$1.invoke(BasicUtil.kt:6)
04-16 14:31:10.589 E/Xposed  ( 2167): 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
04-16 14:31:10.682 E/Xposed  ( 2167): kotlin.KotlinNullPointerException
04-16 14:31:10.682 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.Classes$MMBaseAdapter$2.invoke(Classes.kt:25)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.Classes$MMBaseAdapter$2.invoke(Classes.kt:11)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.Classes.getMMBaseAdapter(Classes.kt)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.hookers.ListViewHider$MMBaseAdapterHooker$1.invoke(ListViewHider.kt:86)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.hookers.ListViewHider$MMBaseAdapterHooker$1.invoke(ListViewHider.kt:17)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:37)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:11)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$2.invoke(XposedUtil.kt:25)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$2.invoke(XposedUtil.kt:11)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil$tryAsynchronously$1.invoke(BasicUtil.kt:18)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil$tryAsynchronously$1.invoke(BasicUtil.kt:6)
04-16 14:31:10.682 E/Xposed  ( 2167): 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Comment by stlyx** [comment]
原来我不是一个人...
手机型号：OnePlus 2
Android 版本：8.1.0 (SDK 27)
Xposed 版本：Starting Xposed version 90-beta2, compiled for SDK 27
Wechat 版本：6.6.6
Wechat Magician版本：2.8.0

**Comment by MikeChongCan** [comment]
@stlyx 现在依旧还是这个问题。

**Comment by MikeChongCan** [comment]
@stlyx 
我升级到了 Android 7.1.1 ，完全可用了。
![screenshot_20180518-104419](https://user-images.githubusercontent.com/2396817/40228383-10e2a576-5a89-11e8-81ba-c9fdc292fdc9.png)

**Comment by Gh0u1L5** [comment]
https://github.com/Gh0u1L5/WechatSpellbook/commit/ef2c9e43cac6781873387a35d947d61ade70de54

这个是之前性能优化出了些问题，在这个commit里面修复掉了，手机运算速度稍微慢一点就会卡到这个bug。
